site_name: GEBI
theme: 'readthedocs'
pages:
  - 'Beranda': 'index.md'
  - 'Wacana':
    - 'Tinjauan': 'wacana/wacana.md'
  - 'Paragraf':
    - 'Tinjauan': 'paragraf/paragraf.md'
  - 'Kalimat':
    - 'Tinjauan': 'kalimat/kalimat.md'
  - 'Kata':
    - 'Tinjauan': 'kata/kata.md'
  - 'Ejaan':
    - 'Tinjauan': 'ejaan/ejaan.md'

